"""加入了 Banned Urls

Revision ID: d4b6b425a92d
Revises: dd927bca1f20
Create Date: 2019-10-23 10:45:45.028294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b6b425a92d'
down_revision = 'dd927bca1f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'banned_url', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'banned_url', type_='unique')
    # ### end Alembic commands ###
