"""删除了作者信息

Revision ID: dd927bca1f20
Revises: b9fa41a4869d
Create Date: 2019-05-30 12:41:46.671794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd927bca1f20'
down_revision = 'b9fa41a4869d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('author', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
