"""empty message

Revision ID: f6e4996fa272
Revises: d4b6b425a92d
Create Date: 2019-10-23 12:41:59.468148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6e4996fa272'
down_revision = 'd4b6b425a92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('book', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('vacant_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.add_column('reading', sa.Column('book_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'reading', 'inventories', ['book_id'], ['id'])
    op.drop_column('reading', 'book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('book', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reading', type_='foreignkey')
    op.drop_column('reading', 'book_id')
    op.drop_table('inventories')
    # ### end Alembic commands ###
